name: applikasi_pelaporan_simrs
description: A new Flutter project.
 
publish_to: 'none'  
 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
 
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.4+1
  dropdown_search: ^2.0.1
  flutter_plus: ^1.0.0
  fluttertoast: ^8.0.8
  http: ^0.13.3
  flutter_slidable: ^1.1.0
  pull_to_refresh: ^2.0.0
  jiffy: ^4.1.0
  timeago: ^3.1.0
  firebase_core: ^1.10.5
  cloud_firestore: ^3.1.4

  # firebase_core: ^1.1.0
  # firebase_messaging: ^9.1.3
  # flutter_local_notifications: ^5.0.0+4
 


dev_dependencies:
  flutter_test:
    sdk: flutter

 
flutter:

  uses-material-design: true
  assets:
    - assets/
 
 
 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
 